services: # список контейнерів
  db: # PostgreSQL база даних
    image: postgres:latest # Який образ брати
    container_name: auto-ria-db
    restart: always # Якщо контейнер падає — перезапустити
    env_file: # Підключає .env, щоб передати змінні середовища
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes: # Зберігає дані БД + дозволяє робити дампи у спільну папку
      - postgres_data:/var/lib/postgresql/data # save DB data persistently in postgres_data
      - ./dumps:/dumps  # mount local ./dumps → container /dumps

  scraper: # Python застосунок (скрапер)
    build: . # 	Збирає Docker image з поточної папки (.) і Dockerfile
    container_name: auto-ria-scraper
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - __pycache__/
            - "*.pyc"
        - action: rebuild
          path: requirements.txt
    depends_on: # не запускати scraper, поки не піднялась БД
      - db
    env_file:
      - .env
    volumes:
      - ./dumps:/dumps
    command: ["python", "-u", "app/main.py"] # Що запускати в контейнері: python main.py

volumes: # опис томів (де зберігаються дані)
  # Docker створить фізичну папку десь у себе, щоб зберігати БД між перезапусками
  postgres_data:
